name: Build firmware and packages

on:
  push:
  schedule:
    - cron: 0 0 * * 1
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build -t builder .
          docker run --rm -it builder

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: redmi_ax6
          path: ./artifact

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 15

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
